[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
; CCCP R2H: known-good Cardputer ADV stack proven by R1W.
platform = espressif32@6.9.0
board = m5stack-stamps3
framework = arduino

lib_deps =
    https://github.com/m5stack/M5GFX.git#0.2.16
    https://github.com/m5stack/M5Unified.git#0.2.10
    https://github.com/m5stack/M5Cardputer.git#1.1.1

lib_compat_mode = strict

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
upload_speed = 921600
