#!/usr/bin/env python3
from pathlib import Path
import sys

C_PATH=Path('components/px68k/x68k/bg.c')
H_PATH=Path('components/px68k/x68k/bg.h')
MARK='PX68K_R56H_SPRITE_TRACE'

def fail(msg, rc=2):
    print('R56h sprite patch ERROR:', msg, file=sys.stderr); sys.exit(rc)

def rw(path, func):
    if not path.is_file(): fail(f'{path} not found; run from G:\\px68k-tab5')
    raw=path.read_bytes(); nl='\r\n' if b'\r\n' in raw else '\n'
    text=raw.decode('utf-8', errors='strict').replace('\r\n','\n')
    text=func(text)
    path.write_bytes(text.replace('\n',nl).encode('utf-8'))

def patch_h(s):
    if MARK in s:
        return s
    anchor='extern\tuint16_t BG_LineBuf[1600];\n'
    if anchor not in s:
        anchor='extern uint16_t BG_LineBuf[1600];\n'
    if anchor not in s: fail('bg.h BG_LineBuf anchor not found',3)
    block='''\n/* PX68K_R56H_SPRITE_TRACE: diagnostic-only sprite dirty path accounting. */\ntypedef struct BG_R56H_SPRITE_TRACE {\n    uint32_t write_changes;\n    uint32_t line_marks;\n    uint32_t visible_line_marks;\n    uint32_t latch_lines;\n    uint32_t reference_lines;\n    uint32_t changed_lines;\n    uint32_t identical_lines;\n    uint32_t bg_enabled_lines;\n    uint32_t last_reg_offset;\n    uint32_t last_old_y;\n    uint32_t last_new_y;\n} BG_R56H_SPRITE_TRACE;\n\nint BG_R56H_IsSpriteDirtyLine(uint32_t y);\nvoid BG_R56H_ConsumeSpriteDirtyLine(uint32_t y);\nvoid BG_R56H_NoteSpriteReferenceResult(uint32_t y, int changed, int bg_enabled);\nvoid BG_R56H_GetSpriteTrace(BG_R56H_SPRITE_TRACE *out);\n'''
    return s.replace(anchor,anchor+block,1)

def patch_c(s):
    if MARK in s:
        # validate full patch
        for tok in ['BG_R56H_IsSpriteDirtyLine','BG_R56H_ConsumeSpriteDirtyLine','r56h_sprite_mark_line','BG_R56H_NoteSpriteReferenceResult']:
            if tok not in s: fail(f'marker present but {tok} missing',4)
        return s
    if 'Sprite_ActiveDirty = 1;' not in s or 'TextDirtyLine[(t)] = 1;' not in s:
        fail('expected sprite dirty baseline anchors not found',5)
    anchor='uint32_t\tVLINEBG = 0;\n'
    if anchor not in s: anchor='uint32_t VLINEBG = 0;\n'
    if anchor not in s: fail('VLINEBG anchor not found',6)
    block='''\n/* PX68K_R56H_SPRITE_TRACE\n * CPU1 owns guest sprite writes and WinDraw line admission, so this compact\n * bitset needs no cross-core lock.  It tags only lines dirtied specifically by\n * sprite-register changes; ordinary TVRAM/GVRAM dirty traffic is untouched. */\nstatic uint32_t s_r56h_sprite_dirty_bits[32];\nstatic BG_R56H_SPRITE_TRACE s_r56h_sprite_trace;\n\nstatic INLINE void r56h_sprite_mark_line(uint32_t y)\n{\n    y &= 0x3ffu;\n    s_r56h_sprite_dirty_bits[y >> 5] |= 1u << (y & 31u);\n    ++s_r56h_sprite_trace.line_marks;\n    if (y < 600u) ++s_r56h_sprite_trace.visible_line_marks;\n}\n\nint BG_R56H_IsSpriteDirtyLine(uint32_t y)\n{\n    y &= 0x3ffu;\n    return (s_r56h_sprite_dirty_bits[y >> 5] & (1u << (y & 31u))) != 0u;\n}\n\nvoid BG_R56H_ConsumeSpriteDirtyLine(uint32_t y)\n{\n    y &= 0x3ffu;\n    s_r56h_sprite_dirty_bits[y >> 5] &= ~(1u << (y & 31u));\n    ++s_r56h_sprite_trace.latch_lines;\n}\n\nvoid BG_R56H_NoteSpriteReferenceResult(uint32_t y, int changed, int bg_enabled)\n{\n    (void)y;\n    ++s_r56h_sprite_trace.reference_lines;\n    if (changed) ++s_r56h_sprite_trace.changed_lines;\n    else ++s_r56h_sprite_trace.identical_lines;\n    if (bg_enabled) ++s_r56h_sprite_trace.bg_enabled_lines;\n}\n\nvoid BG_R56H_GetSpriteTrace(BG_R56H_SPRITE_TRACE *out)\n{\n    if (out) *out = s_r56h_sprite_trace;\n}\n'''
    s=s.replace(anchor,anchor+block,1)
    # reset trace when BG subsystem initializes
    anchor='void BG_Init(void)\n{\n\tuint32_t i;\n'
    if anchor not in s: fail('BG_Init anchor not found',7)
    s=s.replace(anchor,anchor+'\tmemset(s_r56h_sprite_dirty_bits, 0, sizeof(s_r56h_sprite_dirty_bits));\n\tmemset(&s_r56h_sprite_trace, 0, sizeof(s_r56h_sprite_trace));\n',1)
    # mark every TextDirtyLine generated by sprite write
    old_macro = """#define UPDATE_TDL(t)\t\t\t\t\\
{\t\t\t\t\t\t\\
\tint i;\t\t\t\t\t\\
\tfor (i = 0; i < 16; i++) {\t\t\\
\t\tTextDirtyLine[(t)] = 1;\t\t\\
\t\t(t) = ((t) + 1) & 0x3ff;\t\\
\t}\t\t\t\t\t\\
}"""
    new_macro = """#define UPDATE_TDL(t)\t\t\t\t\\
{\t\t\t\t\t\t\\
\tint i;\t\t\t\t\t\\
\tfor (i = 0; i < 16; i++) {\t\t\\
\t\tTextDirtyLine[(t)] = 1;\t\t\\
\t\tr56h_sprite_mark_line((uint32_t)(t));\t\\
\t\t(t) = ((t) + 1) & 0x3ff;\t\\
\t}\t\t\t\t\t\\
}"""
    if old_macro not in s: fail('UPDATE_TDL macro not found',8)
    s=s.replace(old_macro,new_macro,1)
    # changed sprite-write trace
    anchor='\t\tif (Sprite_Regs[adr] != data)\n\t\t{\n\n\t\t\tBG_HOST_SOURCE_BARRIER();\n'
    if anchor not in s: fail('sprite write changed anchor not found',9)
    repl='''\t\tif (Sprite_Regs[adr] != data)\n\t\t{\n\n\t\t\tBG_HOST_SOURCE_BARRIER();\n\t\t\t++s_r56h_sprite_trace.write_changes;\n\t\t\ts_r56h_sprite_trace.last_reg_offset = adr;\n'''
    s=s.replace(anchor,repl,1)
    # record old/new logical dirty bases
    anchor='\t\t\tt = t0 = (*pw + v) & 0x3ff;\n\t\t\tUPDATE_TDL(t);\n'
    if anchor not in s: fail('old sprite Y anchor not found',10)
    s=s.replace(anchor,'\t\t\tt = t0 = (*pw + v) & 0x3ff;\n\t\t\ts_r56h_sprite_trace.last_old_y = t0;\n\t\t\tUPDATE_TDL(t);\n',1)
    anchor='\t\t\tt = (*pw + v) & 0x3ff;\n\t\t\tif (t != t0) {\n'
    if anchor not in s: fail('new sprite Y anchor not found',11)
    s=s.replace(anchor,'\t\t\tt = (*pw + v) & 0x3ff;\n\t\t\ts_r56h_sprite_trace.last_new_y = t;\n\t\t\tif (t != t0) {\n',1)
    return s

rw(H_PATH,patch_h)
rw(C_PATH,patch_c)
print('R56h sprite trace patch applied/verified:', C_PATH, H_PATH)
