#!/usr/bin/env python3
from pathlib import Path
m = Path('src/main.c').read_text(encoding='utf-8')
w = Path('components/px68k/libretro/windraw.c').read_text(encoding='utf-8')
def ck(cond, msg):
    if not cond: raise SystemExit('R56s1 source audit FAIL: ' + msg)
    print('  PASS:', msg)
print('R56s1 source contract audit')
ck('PX68K_R56S_65K_BG_HANDOFF' in w, 'R56s 65K handoff retained')
ck('PX68K_R56S1: cold launcher Host-UI FB0 ownership fence active' in m, 'R56s1 marker present')
ck(m.count('PX68K_R56S1_LAUNCHER_HOST_UI') == 1, 'one cold-launcher ownership marker')
bi=m.index('PX68K_R56S1_LAUNCHER_HOST_UI')
bcall=m.index('tab5_video_begin_host_ui();', bi)
ecall=m.index('tab5_video_end_host_ui();', bcall)
hp=m.index('tab5_log_memory_550("host-preworkers")', ecall)
vi=m.rfind('tab5_video_init();', 0, bi)
ck(vi >= 0 and vi < bi < bcall < ecall < hp, 'cold fence order: video_init < begin < end < host-preworkers')
ck('PX68K_R56Q1: memory-safe sparse exec/CPU0 attribution' in m, 'R56q1 retained')
ck('PX68K_R56R: WinDraw render-path taxonomy fact probe; counters-only' in m, 'R56r retained')
print('R56s1 source contract audit PASS')
