#!/usr/bin/env python3
from pathlib import Path
u=Path('src/tab5_media_ui.cpp').read_text(encoding='utf-8')
m=Path('src/main.c').read_text(encoding='utf-8')
def ck(c,msg):
    if not c: raise SystemExit('R56s2 source audit FAIL: '+msg)
    print('  PASS:',msg)
print('R56s2 source contract audit')
ck('PX68K_R56S2_PSRAM_UI_STRING_BRIDGE' in u, 'browser staging marker present')
ck('char r56s2_path_buf[TAB5_MEDIA_UI_PATH_MAX];' in u, 'full path stack staging present')
ck('char r56s2_name_buf[128];' in u, 'basename stack staging present')
ck('M5.Display.print(r56s2_name);' in u, 'filename draw uses staged string')
ck('M5.Display.print(r56s2_path);' in u, 'path draw uses staged string')
ck('M5.Display.print(empty ? "Empty / eject" : tab5_media_ui_basename(e->path));' not in u, 'old direct filename print removed')
ck('M5.Display.print(empty ? "Leave this slot empty" : e->path);' not in u, 'old direct PSRAM path print removed')
ck('tab5_media_ui_filtered_at(items, count, slot, fidx - 1)' in u, 'selection/filter source unchanged')
ck('PX68K_R56S2: media browser PSRAM-string staging bridge active' in m, 'R56s2 startup marker present')
ck('PX68K_R56S1: cold launcher Host-UI FB0 ownership fence active' in m, 'R56s1 retained')
ck('PX68K_R56S: R56 ownership-safe 65K BG/Sprite host handoff restored' in m, 'R56s retained')
print('R56s2 source contract audit PASS')
